name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web

version: 3.4.3

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  _flutterfire_internals: ^1.2.0
  cloud_firestore_platform_interface:
    git:
      url: https://github.com/aitok-ai/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore_platform_interface
      ref: aitok.us 
  collection: ^1.0.0
  firebase_core:
    git:
      url: https://github.com/aitok-ai/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: aitok.us
  firebase_core_web:
    git:
      url: https://github.com/aitok-ai/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: aitok.us
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.7.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
